name: Run Tests
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore PlaneFX.sln

      - name: Build
        run: dotnet build PlaneFX.sln --no-restore

      - name: Test
        run: dotnet test PlaneFX.sln --no-build
